# 課題: panic! を使ってみよう！

`panic!` は、プログラムが回復不能なエラーに陥ったときに使うよ！💥
例えば、配列の範囲外アクセスとか、絶対に起こっちゃいけない状況で使うんだ。

`Result` は回復可能なエラーに使って、`panic!` は「もうダメだ〜！」って時に使うって覚えておくとイイ感じ👍

## やってみよう！

`check_age` っていう関数を作ってみて！
この関数は、引数で受け取った `age` (年齢、`u32` 型) が 18 未満だったら、`"未成年はアクセス禁止！"` っていうメッセージで `panic!` するようにしてね。
18歳以上だったら、何もせずに普通に終了する感じでOK！

```rust
fn check_age(age: u32) {
    // ここにコードを書く！
}

fn main() {
    check_age(20); // これは panic しないはず
    println!("20歳はOK！");
    check_age(15); // これは panic するはず
    println!("15歳は...ここには到達しないはず！");
}
```

できたら、`lessons/errorHandling_panic/src/main.rs` っていうファイルにコードを書いて、`cargo run` で実行してみてね！
15歳のときにちゃんと panic するか確認して、結果を教えて！💖